# Generated by Django 4.2 on 2023-05-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('member1', models.CharField(blank=True, max_length=128, null=True)),
                ('member2', models.CharField(blank=True, max_length=128, null=True)),
                ('member3', models.CharField(blank=True, max_length=128, null=True)),
                ('member4', models.CharField(blank=True, max_length=128, null=True)),
                ('member5', models.CharField(blank=True, max_length=128, null=True)),
                ('member6', models.CharField(blank=True, max_length=128, null=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='groups/')),
                ('formed', models.IntegerField()),
                ('history', models.FileField(blank=True, null=True, upload_to='histories/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(default=5.0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='rock.group')),
            ],
        ),
    ]
