# Generated by Django 4.2 on 2023-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0002_song_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member7',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
