# Generated by Django 4.2 on 2023-05-29 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rock', '0004_song_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpic', models.ImageField(blank=True, null=True, upload_to='userpics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
